{{- if .Values.persistence.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redisService.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{ end }}